---
name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: Run checks and tests over ${{matrix.otp_vsn}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        otp_vsn: [24,25]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1.15.4
        with:
          otp-version: ${{matrix.otp_vsn}}
          rebar3-version: '3.14'
      - run: rebar3 test
