---
name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}
jobs:
  ci:
    name: Run checks and tests over ${{matrix.otp_vsn}}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        otp_vsn: ['26', '27']
        rebar3_vsn: ['3.23']
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: erlef/setup-beam@8aa8a857c6be0daae6e97272bb299d5b942675a4 # v1.19.0
        id: setup-beam
        with:
          otp-version: ${{matrix.otp_vsn}}
          rebar3-version: ${{matrix.rebar3_vsn}}
      - name: Restore _build
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: |
            _build
            example/_build
          key: "_build-cache-for\
                -os-${{runner.os}}\
                -otp-${{steps.setup-beam.outputs.otp-version}}\
                -rebar3-${{steps.setup-beam.outputs.rebar3-version}}\
                -hash-${{hashFiles('rebar.lock')}}"
      - name: Restore rebar3's cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ~/.cache/rebar3
          key: "rebar3-cache-for\
                -os-${{runner.os}}\
                -otp-${{steps.setup-beam.outputs.otp-version}}\
                -rebar3-${{steps.setup-beam.outputs.rebar3-version}}\
                -hash-${{hashFiles('rebar.lock')}}"
      - name: Format check
        run: rebar3 format --verify
      - run: rebar3 test
      - name: test our example
        run: |
          cd example
          rebar3 release
          _build/default/rel/example/bin/example daemon
          _build/default/rel/example/bin/example ping
      - name: Format check
        run: |
          cd example
          rebar3 format --verify
      - name: check our example
        run: |
          cd example
          rebar3 test
