---
name: Swagger UI

"on":
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: |
          ./.github/workflows/up_swagger.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
